name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version (yy.mm.dd)'
        required: true
      commit_hash:
        description: 'Commit Hash'
        required: true
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: build
        name: Build
        run: ./mvnw -B -ntp --file pom.xml -Pnative package -DskipTests
      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            target/distributions/*.zip
            target/distributions/*.tar.gz 
      - name: 'Release with JReleaser'
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: ./mvnw -B -ntp --file pom.xml -DartifactsDir=artifacts jreleaser:full-release

    
